README.md
example/app.js
package.json
src/react-medium-image-zoom.js

fixes #12 
* * *
This PR should let consumers manually be able to trigger the zoomed state in order to manually open or close it without having to do a hacky click event.
Let's say you have an interface that uses tabs to view different pages. Each tab triggers a `pushState` event so that you can link straight to a given tab; however, instead of blowing away the React elements and rendering a whole new set, you use CSS to hide what shouldn't be visible. The issue arises when you zoom an image and then hit the back button -- the component never unmounts, and therefore you never close the zoom image.
You want to deep link to a zoomed image. On one hand, you could trigger a click manually, but that doesn't seem like the React way, so instead you want to pass an option that says, "Hey, go …

Add isZoomed option

---

example/app.js
package.json
src/react-medium-image-zoom.js

Fixes an issue where if the component isn't destroyed but instead passed a new `src`, it wasn't accepting and using that new `src` and instead was using what was stored in `state`.

Accept new src

---

README.md
example/app.js
package.json
src/react-medium-image-zoom.js

Allows for the component to accept a function that will call back and ask, if provided, whether or not to actually zoom  the image on a click. The issue, #24, makes a good case: sometimes you want to not zoom if you are doing shift + click or control + click, etc. Here's the API for usage:
```js
<ImageZoom
// ...
shouldHandleZoom={(e) => {
if (e.shiftKey) return false;
return true;
}}
/>
```
cc @rsaccon

Should handle zoom func

---

src/react-medium-image-zoom.js

Since `state.image.src` is replaced by a high-res version when `handleUnzoom` is called, checking for an image change by comparing `nextProps` to `this.state` will always return true. The result is that the high-res image is replaced by the low-res and left that way.

Look for image change by comparing props

---

example/app.js
example/src/app.js
package.json
src/react-medium-image-zoom.js

* Adds an example that allows you to use the `j` and `k` keys to zoom & unzoom the first image, respectively. 
* This example pointed out a bug where using the keys to open/close (aka, external commands) and also the click to open/close got out of sync.
* Also fixes an issue where `componentDidUpdate` was calling the `Zoom` component's `handleUnzoom` which in turn triggers the main component's `handleUnzoom`. 
cc @cbothner

Fix external isZoomed issue and also fix unzoom being called twice.

---

README.md
src/react-medium-image-zoom.js

I would like to be able to respond to the user zooming or dismissing the image. This PR adds two simple props of type `func` which default to `() => {}` and are called from `handleZoom()` and `handleUnzoom()` respectively.

Adds optional onZoom and onUnzoom callbacks

---

example/app.js
package.json

@cbothner: forgot to get you to run `npm run build:example` to get the example's output up to date with the component. My bad!
Also adds a bump to version `0.8.0` because of the functionality added.

Rebuild example and 0.8

---

README.md
example/app.js
example/src/app.js
package.json
src/react-medium-image-zoom.js

GH Issue: https://github.com/rpearce/react-medium-image-zoom/issues/35
tl;dr => When `true` and `zoomImage` is included, preload the `zoomImage.src` by including a `<link rel="preload">` for image's source
The original request asked for the link to be included in the `<head>`, but I think this becomes problematic because we're now manipulating the head tag of a page when all we really need to do is do it inline, which still allows for cleanup.
Discussion welcomed either here or on https://github.com/rpearce/react-medium-image-zoom/issues/35.

shouldPreload option

---

example/build/app.js
src/react-medium-image-zoom.js

This PR addresses issue #42.
All props are now passed down to the `Zoom` img component, with special cases for src, srcset, and style.
One note/question: the `hasLoaded` state on the Zoom component is being set in two places
https://github.com/rpearce/react-medium-image-zoom/blob/master/src/react-medium-image-zoom.js#L259
https://github.com/rpearce/react-medium-image-zoom/blob/master/src/react-medium-image-zoom.js#L297
Maybe I'm missing something, but they seem to each reference a difference load event - one being the component mounting, the other being the img element loading. Is this right?

Add srcset support and pass all props to zoomImage

---

README.md
example/build/app.js
example/src/app.js
src/react-medium-image-zoom.js

I think the preload functionality can and should be handled by the package consumer and not by this package. It should be easy enough to recreate this functionality:
```js
<span>
<link rel="preload" href={...} as="image" />
<ImageZoom ... />
</span>
```
This'll be included in the v2.0 release.
cc @ismay for review

Remove preload functionality

---

.npmignore
README.md
example/build/app.js
example/src/app.js
package-lock.json
package.json
src/ImageZoom.js
src/helpers.js
stories/DefaultStyles.js
stories/ShouldHandleZoom.js
stories/ShouldReplaceImage.js
stories/ShouldRespectMaxDimension.js
stories/ZoomImage.js

Fixes #54 
I've classified this as a bug. If you pass `shouldRespectMaxDimension={true}`, then that specification should include the following:
* if the image rendered on the screen is the largest version of the image that we're going to get, then don't bother showing any zooming capabilities, as the alternative is just moving the exact same image to the center of the screen .
* * *
This PR also adds a number of unnecessary files to the `.npmignore` and updates the storybook.

Don't provide zoom option if it can't actually be zoomed

---

.eslintrc
example/build/app.js
src/ImageZoom.js
stories/ShouldRespectTabIndex.js

Fixes #77 
* These changes isolate cached state to image `src` (required to support high/low-res versions), allowing all other image attributes (`alt`, `className`, `tabIndex`, etc) to change without also first changing the image source. 
* Bonus fixed subtle issue with unzoomable images being able to receive keyboard focus.
* Relaxed a couple of the lint errors to warnings to make debugging easier.

Image attribute mutability

---

docs/app.js
src/ImageZoom.js

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/139.
cc @babyPrince

Fix zoomMargin not accepting number as string

---

docs/app.js
src/ImageZoom.js

This pull request closes JS error seen in production:
Whenever we're using a ref that's set post-mount it should be treated as though it won't always exist. I'm not sure what the correct "stable" branch is, let me know if the base needs changing.

Fixes JS error when _allowTabNavigation is called before image ref

---

package.json
src/ImageZoom.js
src/Overlay.js

This pull request doesn't fix (the following issue) #143 but addresses the removal of now deprecated methods in React 16 to be compatible with `<React.StrictMode>`.
Since it now uses the `getDerivedStateFromProps` lifecycle method in its actual state, I set the minimum required version of `react` and `react-dom` to `^16.4.0` which [includes the bugfix](https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops) for this method.
I don't have time to improve it better (switching to hooks, etc...) right now, but would be happy to do so when I can find some spare time later.

Update methods to be compatible with React.StrictMode

---

src/ImageZoom.js

Preact doesn't support Array, hence used Fragment.
Reference URL: https://github.com/preactjs/preact/issues/929
This pull request closes (past link to GitHub issue here).
- [ ✅] make sure this PR is set to merge to the correct `X-0-stable` branch
- [ ✅] add a Storybook example (if necessary)
- [ ✅] manually test all the Storybook examples
- [ ✅] run `$ yarn run build` to build the project code & static example
- [ ✅] check that the example in `example/build/index.html` works: `$ open example/build/index.html`

Used Fragment instead of Array in render method to support Preact

---

README.md

Quick change. Since GitHub allows copy from snippets directly, it was copying the $ too which does not work when pasted into a terminal.

Remove $ from install instructions

---

source/Controlled.tsx
source/Uncontrolled.tsx

This pull request closes #302
I have made sure to:

fix: replace deprecated ReactType types with ElementType

---

README.md
package-lock.json
package.json

* replace npm-run-all with concurrently
* rm babel-loader (unused) and coveralls (not finding it valuable)

Chore: package.json build updates

---

README.md

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/335

Docs: add migrating from v4 to v5 documentation

---

tsconfig.json

TS was complaining about this:
```
Property 'height' does not exist on type 'CSSProperties'
```
Which was weird. Setting `moduleResolution` to `nodenext` seems to resolve it.

Fix weird CSSProperties issue by setting moduleResolution to nodenext

---

CHANGELOG.md
README.md
package-lock.json
package.json
source/Controlled.tsx
stories/Img.stories.tsx
stories/base.css

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/356 ~by adding `wrapElement` back to the API. Honestly, I forgot about https://github.com/rpearce/react-medium-image-zoom/pull/238~.
~However, allowing `<span>` or `<p>` or any element that can only have "Phrasing content" (inline elements, really) as a parent creates an issue, for the `<dialog>` element is block-level. To remediate this, I'm seeing if leveraging a portal for the `<dialog>` is a wise decision.~ It seems that the portal might be the way to go. Continued testing will have the final say.

Portalize <dialog> to avoid invalid HTML issues

---

source/Controlled.tsx
stories/Img.stories.tsx
stories/base.css

This pull request addresses https://github.com/rpearce/react-medium-image-zoom/issues/357
1. Run the storybook locally
2. Go to http://localhost:6006/?path=/story/img--delayed-display-none
3. Ensure you can use the zoom after the image is shown

Fix not supporting display: none; images

---

source/utils.ts
stories/Img.stories.tsx

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/350 by finally solving the `zoomMargin` math issue.
Has this _ever_ measured correctly? [The same math has been used since v2 >5 years ago](https://github.com/rpearce/react-medium-image-zoom/blob/e9d138d6b521006d8d02e646db7cdfc3dcbb07c2/src/helpers.js#L34-L38).
1. Run the storybook examples: `npm start`
2. Go to the `Zoom Margin` story
3. Ensure the zoomed image is offset from the window by the appropriate amount
4. Use a portrait image and see how that works

Fix zoomMargin measuring

---

source/Controlled.tsx

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/369 by ensuring zoomed SVGs are unzoomed on click.
The logic here, https://github.com/rpearce/react-medium-image-zoom/blob/8cb689aec030cbba19245ae069b10604df809cc0/source/Controlled.tsx#L445, isn't the best thing ever, but it's to try and prevent unzooming if people have customized modal content that somebody clicks on. While I could have it check for an SVG here, `e.target` could potentally be a `<path />` or other SVG sub element, so that isn't a good idea.

Fix clicking to unzoom SVG elements

---

source/Controlled.tsx

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/378 by calling `e.preventDefault()` on the `onCancel` `<dialog>` event.
1. Run the storybook examples locally
2. Go to the `Custom Modal Styles` one
3. Click it to zoom
4. Click it again to unzoom, but press Escape while it is unzooming
5. Ensure that the unzooming continues smoothly

Fix: Pressing escape while unzooming

---

source/Controlled.tsx
source/utils.ts

Sometimes the image has already been loaded and it can't trigger the `onload` event. So we should check if the image has been loaded before binding the event, and if it has been loaded, we can call `setLoaded` directly. Otherwise, bind the `onload` event.
Take the screenshot as an example:
Because `epid4.png` has already been loaded, so the `onload` event doesn't be triggered as expected and the DOM shows `data-rmiz-content="not-found"`.
After my change, it works!
Please let me know if any questions.
Thanks.

[BugFix] Image has already been loaded

---

source/Controlled.tsx
source/utils.ts

This PR addresses #375
When an element (or it's "container" concept) has a width and/or height of `0`, the `getScale` function tries to do some math that results in `Infinity`. When it then tried to multiply a dimension of `0` by the resulting scale (`Infinity`), it returned `NaN`, so we would end up with values like `{ width: NaN, height: NaN }` that were used in `style` tags on an `<img />`.
To resolve this, if the values for `containerHeight` or `containerWidth` are falsy (e.g. `null`, `undefined`, or `0`) for any reason, we bail from `getScale()` and return a scale of `1`.
Here is the simplest possible reproducible case:
1. Clone the project
1. Run `npm i`
1. Run `npm start`
1. Navigate to http://localhost:6006/?path=/story/img--regular
1. Open your JS web console
1. Make this change …

fix(375): NaN invalid CSS width issue

---

source/utils.ts

This PR addresses #406 
This fixes an issue where we were unsafely assuming an SVG's parent element existed, and trying to access a bounding rect property on it failed, for getting the bounding client rect failed silently. In essence, `undefined.left` doesn't work.
The fix is to rely on the `imgEl`'s rect if the parent isn't available.
1. Clone this repository
2. Run `npm i`
3. Check out this branch
4. Run `npm start`
5. Test all the SVG examples
6. Ensure a `<div>` example works
7. Ensure a regular `<img />` example works

fix(406): SVG missing parent error

---

source/Controlled.tsx

Fixes https://github.com/rpearce/react-medium-image-zoom/issues/412 by 
In a recent bugfix to support older browsers (#402), I accidentally left ouf the `[role="img"]` selector from the DOM query, thereby making `<div role="img">` instances no longer work.
1. Clone this repository
2. Run `npm i --no-save`
3. Run `npm start`
4. Go to the Galleries > Div example
5. It should work as expected

fix(412): zoom when role=img

---

source/utils.ts

If we know we're working with a `div` image, then there's no need for us to have the `getImgObjectFitStyle(...)` code run. This also ensures that the logic here does indeed return booleans.
Not a huge risk here: images should still zoom with object fit cover (for example), and div images should still zoom.

chore: cleanup style modal img code

---

.github/workflows/main.yml

Not much to see here. This removes a playwright install from CI steps that was accidentally left in.

chore: remove unused CI step (playwright install)

---

source/Controlled.tsx

This pull request addresses https://github.com/rpearce/react-medium-image-zoom/issues/421 by re-enabling body scroll if we're not in an `UNLOADED` state when unmounting.
1. Clone this repo
2. Checkout this branch
3. Run `npm i`
4. Run `npm start`
5. In your browser, shrink the browser window so it's really small and go to one of the gallery pages
6. Click on an image so it's zoomed
7. Navigate to another gallery page. You should be able to scroll that page
8. For extra testing, do these same steps with other examples in various states (unzooming, unzoomed, for example)

fix(421): re-enable body scroll when unmounting

---

README.md

Closes https://github.com/rpearce/react-medium-image-zoom/issues/425
N/A

docs(425): add Image decode() Jest error info to README

---

source/Controlled.tsx

Fixes #430. cc @steven-tey
There's a weird issue, probably related to Safari's `:focus-visible` behavior or their `<dialog>` implementation, where the `<dialog>` element's button doesn't receive focus when it's opened. It could also be a race condition because of the animation.
Regardless, let's try listening for `Escape` at the `document` level when we zoom an image. We need to make sure we provide the `useCapture` option and get to the event first so we can intercept it and don't trigger the default `<dialog>` `Escape` behavior so we can animate zooming out.
1. Temporarily install `react-medium-image-zoom@5.1.7-rc.0`
2. Run your code
4. See if there are any issues using `Escape` when the images are zoomed!
1. Clone this project and go to the project directory
2. Run `npm i && npm start` …

fix(430): ESC intermittently not working in Safari

---

CONTRIBUTING.md
source/Controlled.tsx
source/styles.css

Address a few issues I've discovered when using the library in my project.
1. Implements the style fix for #433 as suggested by @rpearce 
2. Allows to zoom on the already zoomed image with ctrl + wheel and pinch to zoom gestures on desktop
3. Triggers unzoom on `touchmove` instead of `touchstart`. That is much closer to the behaviour on Medium (https://medium.design/image-zoom-on-medium-24d146fc0c20). Handling unzoom on `touchend` leads to nothing happening with the image while I touch-scroll until I lift my finger up.
Plus, renames `master` to `main` in CONTRIBUTING.md; otherwise, the instructions don't fully work.
1. Clone this project and go to the project directory
2. Run `npm ci && npm start`
3. Go to http://localhost:6006 (or equivalent local IP if you use a mobile device as …

Fixes for the zoom behaviour and overlay height in iOS Safari

---

.all-contributorsrc
CHANGELOG.md
README.md
package-lock.json
package.json

chore: release v5.1.8

---

README.md

fix(README) tag is not closed

---

source/Controlled.tsx

This pull request addresses #429. The problem is that the `appendChild` action is written at the top level. It can run only once after being imported so it's not working after refreshing. And I tried to write it in `componentDidMount`. I'm not sure if it's an appropriate and efficient way. But it fixed the bug.
Run `npm run test-storybook`. All testing passed.
First time to open a pull request for a bug fix. I'm not familiar with the class component.

fix(429): next 13 edge runtime bug

---

README.md

Since [it appears bundlephobia is dead or dying](https://github.com/pastelsky/bundlephobia/issues/863), let's try using the newer bundlejs.
Open the file and make sure the image works!

chore: try bundlejs badge since bundlephobia seems dead

---

source/Controlled.tsx

In theory, this fixes https://github.com/rpearce/react-medium-image-zoom/issues/436, and is a response to https://github.com/rpearce/react-medium-image-zoom/pull/472, but I'm not opposed to having that as an option, anyway.
The goal with this work is to allow users to pinch-to-zoom in on RMIZ-zoomed images and pan around without being unzoomed (not a nice experience). Once they return the zoom to the normal browser zoom level, then swiping will close the image.
NOTE: I still need to test this on an Android phone and an iPad.
1. Clone the repo and checkout this branch: `fix/pinch-zoom`
2. `npm i --no-save && npm start`
3. Get your local IP address by running this (should work...)
```
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v …
```

fix: support pinch-to-zoom behavior

---

.github/dependabot.yml

Not much to see here. This groups some dependabot deps and sets it to only open PRs for ones mentioned in package.json

chore: try dependabot differently

---

source/Controlled.tsx
source/Uncontrolled.tsx
source/utils.ts
stories/Galleries.stories.tsx

This clears up some "what API does this even come from?" questions and also has the added benefit of better gzip compression due to the repeated strings and not requiring extra variables for destructured objects.
```
orig: 15144 bytes
gzip: 4518 bytes
orig: 15165 bytes
gzip: 4509 bytes
```

chore: get better gzip compression via React namespacing

---

README.md
source/Controlled.tsx
stories/Img.stories.tsx

This builds on https://github.com/rpearce/react-medium-image-zoom/pull/472 by doing the following:
* Alphabetizes the `canSwipeToUnzoom` and `swipeToUnzoomThreshold`
* Adds info for them to `README.md`
* Adds a storybook story for each (only relevant to touchscreen devices)

chore: backfill docs and style for 2 new swipe to unzoom features

---

.github/workflows/main.yml
rollup.config.js
source/Controlled.tsx

Fixes #470 by only allowing zooming when we have a loaded image.
1. Checkout this branch
2. Run `npm start`
3. Go to http://localhost:6006/iframe.html?args=&id=img--inline-image&viewMode=story in Chrome
4. Open the Network tab and choose "Fast 3G" for throttling
5. Hard-refresh the page to force an image re-download
6. When the image starts loading in, start clicking on it. Nothing should happen. When it has loaded, the zooming behavior should more or less work

fix: clicking image before it loads

---

.github/dependabot.yml
package-lock.json
package.json

* renames dependabot groups to be a little more generic
* ignores `eslint@9`
* moves accidental dev dep out of dependencies

chore: fix bad dep and dependabot things

---

source/Controlled.tsx

Fixes https://github.com/rpearce/react-medium-image-zoom/issues/439
If someone is using a mouse with a scroll wheel in Windows using Chrome or Edge, and they click to zoom an image while the scroll wheel is still going, they would end up in an intermediary, broken state.
This fixes the issue by ensuring that the `wheel` event, which is used for closing the zoomed image dialog, isn't able to be triggered until the image has zoomed fully.
I repro'd this issue using Parallels and doing what was described above (and is also shown in a video on the issue).

fix: weird state where wheel event fires too early

---

source/utils.ts
stories/Img.stories.tsx

If an `<img />` element has a `src` that is an SVG that has no `width` nor `height` defined, we got into a weird spot where the loaded element had `naturalWidth` and `naturalHeight` of `0`. This can differ between browsers, but most notably in Firefox. In Firefox, since this is `0`, the object fit calculations were dividing by zero, leading the scaling factor to go from its correct amount (scale to the browser window) to not scaling whatsoever and just centering the image on the screen at the same size it was rendered at. The fix here is to do what we do for other calculation functions and fallback to the image's rect measurements.
This also makes sure we use `decoding="async"` on test images to make sure we're always testing the laziest images possible!

fix: img SVGs with no dimensions not scaling

---

source/Controlled.tsx

Fixes a weird, doesn't-always-happen little flicker when an image is unzoomed. It's particularly noticeable if a page takes up a bunch of memory, and it's more reproducible in Safari in that scenario.
This moves the official closing of the `<dialog>` element and re-enabling of body scroll until after the `setState` gets a change to run. I think the issue is that the React internals would sometimes take too long, and we'd remove the dialog before the component had a chance to update and know that it was an `UNLOADED` `modalState`, thus having the original image still with `visibility: hidden;` for a split second before coming back.

fix: flickering after unzooming

---

package.json
source/Controlled.tsx
source/styles.css
stories/Img.stories.tsx
stories/base.css

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/627, and the only real commit to look at is https://github.com/rpearce/react-medium-image-zoom/pull/638/commits/302ed09553b60e1a054e544180e7c271679f64dd.
This was a weird one. I don't know how the ghost element is working correctly in Chrome & Firefox, but in Safari, `[data-rmiz]` having `position: relative;` makes its ghost child, which is `position: absolute;` be offset quite a bit, and it's even worse the longer a page is. It may only surface when people use `<Zoom wrapElement="span" ...>`, and the parent element goes to being `inline`.
A quick solution is to simply remove that style, but I noticed that there was some funkyness & inconsistency with how the ghost rendered in a few situations. Instead of …

fix: ghost not being styled right

---

.changeset/bright-snakes-laugh.md
source/Controlled.tsx

This solves an issue where Safari is unreliable with when it's going to call `transitionend` events when significant memory is being used on a webpage. Additionally, it does the following:
* refactors the state change events to be handled together after `componentDidUpdate`
* uses a single `transitionend` event handler to cover both the zoom and unzoom transition ending events
* critically, it adds a timeout event that takes the original transition duration, plus 50ms, and runs a function that ensures the transition end callback runs; this callback is responsible for resetting the modal state, and that re-enables body scrolling and closes the modal

fix: unzooming getting stuck in Safari

---

.changeset/good-mangos-unite.md
rollup.config.js

Fixes https://github.com/rpearce/react-medium-image-zoom/issues/623 by including `'use client';` at the top of the exported ESM file.
1. Clone the repo and `cd` into it
2. `git switch fix/use-client`
3. `npm i --no-save`
4. `npm run build`
5. `cat dist/index.js` — this should have `'use client';` at the top

fix: include 'use client' directive in ESM output

---

.changeset/flat-readers-return.md
source/Controlled.tsx

Closes https://github.com/rpearce/react-medium-image-zoom/issues/746
I added all the deps from https://stackblitz.com/edit/vitejs-vite-djxwwz?file=src%2FApp.tsx,package.json and set up a Storybook demo that recreated the issue. I then tried a few things and realized that the zoom component's `<dialog>`'s `close` event firing was what was causing the issue with this specific library, so stopping our `close` event propagation is the fix here.

fix: zooming inside a parent dialog that has a close handler

---

stories/Img.stories.tsx
stories/base.css

This PR adds a story under `img` in the story book. Showing user how to add loading spinner with the help of `ZoomContent` when a `ZoomImg` is provided. The loader was barely noticeble cause the the image get's loaded and cached very quickly. So I added a `useEffect` which delays the loader to 1 second.  The loading spinner is shown everytime the img is zoomed. But in a real-world scenario the loader is shown only once (browser caches the image for next time)
1. Start the story book server `pnpm run storybook`
2. Go to `http://localhost:6006/?path=/story/img--zoom-img-loader`
3. You should see an example
4. Zoom the image you should see a loading spinner
5. Spinner should render everytime `ZoomImgModal` loads

ZoomImg loading storybook example

---

.changeset/chilly-months-win.md
.changeset/red-dingos-know.md
README.md
source/Controlled.tsx
source/Uncontrolled.tsx
stories/Img.stories.tsx
stories/base.css

Closes https://github.com/rpearce/react-medium-image-zoom/issues/939
There is no valid usage of this library inside an `<a>` or `<button>`, for that generates not only invalid HTML but incorrect accessibility. However, there is a use-case where the parent has a click event for tap/mouse users, and the accessibility is controlled elsewhere (checkbox).
1. Run the project locally on this branch: `pnpm start`
2. Navigate to http://localhost:6006/?path=/story/img--select-cards
3. Clicking the zoom/unzoom should have no effect on the selected state. Clicking the whitespace around the cards, or the checkboxes, should toggle the checkboxes.

fix: prevent zoom click even propagation
