rpearce/react-medium-image-zoom

example/app.js
package.json
src/react-medium-image-zoom.js

fixes #2 
Resizing the viewport will re-render the zoomed image and all that goes with it.
Also added an npm script for building all the things.

Window resize

---

example/app.js
package.json
src/react-medium-image-zoom.js

fixes #1 
Still could use a little optimization, but looks great

Fix scroll

---

README.md
example/app.js
package.json
src/react-medium-image-zoom.js

Make ESC button close zoom

---

.gitignore
README.md
example/app.js
example/src/app.js
package.json
src/react-medium-image-zoom.js

A stab at adding an option to respect the max width or height of an image when zooming it. This won't work with also providing zoomImage option because of how all this stuff is calculated

Respect max dimension

---

README.md
example/app.js
package.json
src/react-medium-image-zoom.js

Allow for full overriding of default styles

---

package.json
src/react-medium-image-zoom.js

Fix PropTypes deprecation

---

README.md
example/build/app.js
package.json
yarn.lock

cc @ismay and this PR: https://github.com/rpearce/react-medium-image-zoom/pull/39

Proptypes update

---

Makefile
package.json

Now a build means you just call
```
$ make
```
from the terminal

In order to solidify dev process to compile all the things easily, we'll go with make

---

example/build/app.js
package.json
src/react-medium-image-zoom.js

Overlay style precedence

---

Makefile
README.md
index.js
nodemon.json
package.json
yarn.lock

tl;dr => better dev experience
* added a local dev server that watches for changes to `src/` and `example/src/`
* updated README.md

Improve dev experience

---

.all-contributorsrc
README.md
package-lock.json
package.json
yarn.lock

Add contributors

---

.storybook/addons.js
.storybook/config.js
CHANGELOG.md
Makefile
README.md
example/build/app.js
example/src/app.js
package-lock.json
package.json
src/ImageZoom.js
stories/Controlled.js
stories/DefaultStyles.js
stories/ShouldHandleZoom.js
stories/ShouldReplaceImage.js
stories/ShouldRespectMaxDimension.js
stories/Uncontrolled.js
stories/Welcome.js
stories/ZoomImage.js
stories/index.js
yarn.lock

Added storybook and a couple of bug fixes. bumps to v2.0.2

---

example/build/app.js
src/EventsWrapper.js
src/ImageZoom.js
src/Zoom.js
src/keyboardEvents.js
stories/ShouldRespectTabIndex.js
stories/index.js

Addresses [keyboard accessibility](https://github.com/rpearce/react-medium-image-zoom/issues/70) for 2.0 (pre-React 16 upgrade)

keyboard accessibility

---

example/build/app.js
src/EventsWrapper.js
src/ImageZoom.js
src/Zoom.js
src/keyboardEvents.js
stories/ShouldRespectTabIndex.js
stories/index.js

Addresses [keyboard accessibility](https://github.com/rpearce/react-medium-image-zoom/issues/70) for 3.0.1 (post-React 16 upgrade)

keyboard accessibility (v3)

---

README.md
package-lock.json
package.json

This is what I get for doing this late at night and merging my own stuff.

3.0.4 – fix stupid readme bug

---

example/build/app.js
src/EventsWrapper.js
src/keyboardEvents.js

This pull request introduces changes from #97 into v3.

2.0.7 parity

---

CHANGELOG.md
example/build/app.js
package-lock.json
package.json
src/EventsWrapper.js
src/ImageZoom.js

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/106.

v3.0.6 – fix for #106

---

AUTHORS
CHANGELOG.md
package-lock.json
package.json

AUTHORS file for NPM

---

.babelrc
.eslintrc
CHANGELOG.md
example/build/app.js
example/build/index.html
package-lock.json
package.json
src/Zoom.js
yarn.lock

This pull request closes #96 .
@kingdido999: what do you think of this solution? Seems to be good, though I feel _meh_ about adding `100ms` onto the load time. Would you do a Firefox check [here](https://github.com/rpearce/react-medium-image-zoom/pull/117/files#diff-ac72cd8615dec0dd5b0fda073454a248R85)? _Update: I did that Firefox check._

fix firefox flicker #96

---

docs/app.js
src/Zoom.js

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/119.

Removed isFirefox check from Zoom.js

---

CHANGELOG.md
docs/app.js
package-lock.json
package.json
src/ImageZoom.js
src/Zoom.js
stories/ZoomOnLoad.js
stories/index.js

This pull request closes https://github.com/rpearce/react-medium-image-zoom/pull/129.

Fix zoom on load

---

src/Zoom.js

Calculate "imageCenterX" with "clientWidth" to include the scrollbar width.

Calculate imageCenterX with clientWidth

---

docs/app.js
src/ImageZoom.js
stories/DisableOnError.js
stories/index.js

This pull request closes #137.

Disable on image fetch error

---

source/Activated.js

This pull request closes (past link to GitHub issue here).

Handle Escape Click for Zoomed images

---

source/Activated.js

Thanks to @spencerfdavis's PR for `useWindowSize`, I refactored the style logic into `getStyle` and refactored `getScale`, as well. These should now be pure functions, and we'll circle back to test the functions in the near future.
* run `$ yarn start`

refactor activated code a bit

---

.storybook/addons.js
.storybook/presets.js
API.md
package.json
source/Activated.css
source/Activated.js
source/Uncontrolled.js
source/lib/getModalContentStyle.js
source/lib/getModalOverlayStyle.js
source/lib/getScale.js
source/lib/toDurationString.js
stories.js
yarn.lock

Closes https://github.com/rpearce/react-medium-image-zoom/issues/174 and also accepts the following:
| Prop | Type | Required | Default  | Details |
| ---  | --- | ---  | --- | --- |
| `closeText` | `String` | no | `'Unzoom Image'` | Accessible label text for when you want to unzoom |
| `openTextText` | `String` | no | `'Zoom Image'` | Accessible label text for when you want to zoom |
| `overlayBgColorEnd` | `String` | no | `'rgba(255, 255, 255, 0.95)'` | Modal overlay background color at end of zoom |
| `overlayBgColorStart` | `String` | no | `'rgba(255, 255, 255, 0)'` | Modal overlay background color at start of zoom |
| `portalEl` | `Element` | no | `document.body` | [DOM Element](https://developer.mozilla.org/en-US/docs/Web/API/element) to which we will append the zoom modal |
| …

Customization props & extracting some helper fns to own modules

---

CHANGELOG.md
README.md
package.json

v4 release

---

.travis.yml
package.json
source/Controlled.tsx
source/ControlledActivated.tsx
source/Uncontrolled.tsx
source/UncontrolledActivated.tsx

Updates deprecated `React.SFC` to `React.FC`

Chore: convert SFC to FC

---

source/ControlledActivated.tsx

This pull request closes #246 
this makes sense)

Fix unnecessary stopPropagation call on keydown

---

README.md

This pull request closes (past link to GitHub issue here)
I have made sure to:

mention support for <video> tag as well

---

CHANGELOG.md
package.json

Chore: React 18

---

.eslintignore
package.json
tsconfig.json

* Set tsconfig to not build a `sourceMap`
* slightly adjust a couple of package.json things
* update .eslintignore

Chore: misc minor changes

---

package-lock.json
package.json
tsconfig.json

* Also rm `AUTHORS` from `files` in `package.json`, for it no longer exists

Chore: update some dev deps, don't allowUnreachableCode, and only include our source in tsconfig

---

.dockerignore
.github/workflows/main.yml
Dockerfile
docker-compose.yml
package.json

As any onlookers can see from the commits, I tried ot have the GitHub workflow run the docker commands, but there were permissions issues I couldn't get around, and it's not worth it to keep trying here.

Chore: dockerize the component

---

.all-contributorsrc
README.md
stories/Img.stories.tsx
stories/base.css

This pull request closes https://github.com/rpearce/react-medium-image-zoom/issues/333

Docs: add style customization documentation

---

tsconfig.json

Undo setting moduleResolution nodenext because of import issues

---

package-lock.json
package.json

Not much to see here other than staying on top of dependencies (that aren't broken in their latest versions).

Upgrade some dev deps

---

flake.lock
flake.nix
shell.nix

This PR adds some `nix` files for development purposes.

Add nix dev files

---

CHANGELOG.md
source/styles.css

This pull request addresses #359
1. Open the examples via `npm start`
2. Go to your system's accessibility settings and set the motion preferences to `Reduce motion` (what it is on macOS, for example)
3. Ensure that the animations are non-existent and everything still works

Support prefers-reduced-motion

---

README.md

This pull request addresses the lack of documentation for the new custom zoom modal content feature by:
* Adding it to the features list
* Adding a link to the storybook example
* Providing a simple example describing how someone would use this feature

Add documentation to README for customizing the zoom modal content

---

source/Controlled.tsx

Leverages VSCode's use of comments to make things easier to understand at a glance:
N/A

chore: update code comments to get better experience in VSCode

---

CHANGELOG.md
package-lock.json
package.json

This gets everything together for the `v5.1.5` release

chore: release v5.1.5

---

README.md

chore: add periods to API docs to help readers

---

.all-contributorsrc
CHANGELOG.md
README.md
package.json

Release v.5.1.7 and add @steven-tey as an all contributor for #430.
* https://github.com/rpearce/react-medium-image-zoom/pull/431

chore: release v5.1.7

---

.all-contributorsrc
CHANGELOG.md
README.md
package-lock.json
package.json

chore: release v5.1.9

---

CHANGELOG.md
package-lock.json
package.json

chore: release v5.1.11

---

.all-contributorsrc
CHANGELOG.md
README.md
package-lock.json
package.json

chore(release): v5.2.1

---

CHANGELOG.md
package-lock.json
package.json

Not much to see here... releasing `5.2.2`

chore(release): v5.2.2

---

package.json

Closes https://github.com/rpearce/react-medium-image-zoom/issues/538

chore: use prepack script instead of prepublishOnly

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v5.2.4

---

.all-contributorsrc
CHANGELOG.md
README.md
package-lock.json
package.json

Not much to see here. Just release info.

chore: release v5.2.5

---

.storybook/main.cjs
package-lock.json
package.json

* patch bump to `rollup`
* rm deprecated `@storybook/addon-mdx-gfm` (which doesn't really appear to even be used for GitHub-flavored markdown in here?)

chore(deps): bump rollup (patch); rm @storybook/addon-mdx-gfm

---

CHANGELOG.md
package-lock.json
package.json

chore(release): v5.2.8

---

.github/workflows/main.yml
package-lock.json

fix: build

---

.github/dependabot.yml

Not much to see here; Dependabot consolidation.

chore(deps): group all dev dep upgrades

---

package-lock.json
package.json

* update package dependencies to react 19

chore: update to react 19

---

README.md

Fix a typo / syntax error in the given example
1. Do this
2. Do that
3. It should work

fix typo in example / syntax error

---

.all-contributorsrc
.changeset/thick-boxes-stare.md
.storybook/main.ts
README.md
source/Controlled.tsx

Fixes https://github.com/rpearce/react-medium-image-zoom/issues/830#issuecomment-2668727921

fix: crossorigin images

---

package.json

Make sure we note which build scripts we're making sure we ignore.

chore: ignore esbuild build script

---

package.json

chore: pnpm@10.16.1
